### ISSUE TITLE
Mount all snapshot closest to chosen date/time

### ISSUE THREAD

**Issue by kkerr2005** [Actifio/AGMPowerLib#2] opened 2020-08-06 15:55 UTC
Hi Anthony,

Just one thing that would be nice, is the ability to list all snapshot images closest to a point in time and then mount them.

Im trying to do something with comparing the backups dates, but its slow progress.

anything you can do would be a great help

thanks

**Comment by aussiestorblog** [comment] 2020-08-07 00:51
So here is an example of logic to select a range.
First I list all snaps:

```
PS /Users/anthony> Get-AGMImage -filtervalue "appid=261762&jobclass=snapshot" | select-object consistencydate

consistencydate
---------------
2020-08-06 11:23:47
2020-08-05 11:44:28
2020-08-04 11:26:00
2019-11-27 13:18:54
2019-11-25 13:16:53
```

I can set an upper limit:

```
PS /Users/anthony> Get-AGMImage -filtervalue "appid=261762&jobclass=snapshot&consistencydate<2020-08-06 11:23:46" | select consistencydate

consistencydate
---------------
2020-08-05 11:44:28
2020-08-04 11:26:00
2019-11-27 13:18:54
2019-11-25 13:16:53
```

And a lower limit:

```
PS /Users/anthony> Get-AGMImage -filtervalue "appid=261762&jobclass=snapshot&consistencydate<2020-08-06 11:23:46&consistencydate>2019-11-26 13:00" | select consistencydate

consistencydate
---------------
2020-08-05 11:44:28
2020-08-04 11:26:00
2019-11-27 13:18:54

PS /Users/anthony>
```

Just need to determine the best logic:

1) Closest to point.  -  but how close? 

We could set a tolerance before and afterwards,
i.e. up to 4 hours earlier and 6 hours later...

If user doesn't specify a tolerance, what should we use?

If they give us two dates we could just use the interval as our range.
If they give us one date and say  +2 hours or -2 hours or both.

2)  Mount all images?

That could be a lot..   Do we default to say 5 and let the user specify if they are want more?

3)  type of mount

I think your request could apply to any app type, but as you can see we haven't written many app specific modules yet.   Which app type (source) are you thinking of first?   If VMs..  then mount as new VMs, or mount to existing VM?

**Comment by kkerr2005** [comment] 2020-08-07 08:24
Thanks for your prompt response 


Im thinking of VM's for now, just providing the upper and lower values will probably do it. I think what I need is just a list of Image ID's or names including the appname. Then i can just iterate through the list and mount. An optional tolerance would be a nice to have.

Ill continue working with the filtervalues for now.

**Comment by aussiestorblog** [comment] 2020-08-09 07:00
Ok, so Just uploaded version 0.0.0.4 which has two new functions:

Get-AGMLibImageRange
New-AGMLibMultiVM

So with Get-AGMLibImageRange we build a list of recovery images
For instance this command will get a list of images for appid 4771 four days either side of the nominated date
```
Get-AGMLibImageRange -appid 4771 -olderlimit -newerlimit 4 -consistencydate "2020-08-04 12:00"
```
Instead of appid, you can use app name or fuzzyappname or apptype.
You can also specify -hours to change older limit and newer limit from days to hours

So for my test I grabbed all VM images created in the last day and got 28.
Note I specified appliance name to make sure I only worked with one appliance.

```
PS /Users/anthony/git/AGMPowerLib> $imagelist = Get-AGMLibImageRange -apptype VMBackup -appliancename sa-sky -olderlimit 1
PS /Users/anthony/git/AGMPowerLib> $imagelist.count
28
```
I learned my vcenter host ID and set id:

```
PS /Users/anthony/git/AGMPowerLib> Get-AGMHost -filtervalue "isvcenterhost=true" | select id,hostname,srcid

id      hostname                  srcid
--      --------                  -----
5552172 scvmm.sa.actifio.com      4661
5552150 hq-vcenter.sa.actifio.com 4460
5534713 vcenter-dr.sa.actifio.com 4371

PS /Users/anthony/git/AGMPowerLib> $vcenterid = 5552150
```

I learned my ESXHost IDs and made a simple array

```
PS /Users/anthony/git/AGMPowerLib> Get-AGMHost -filtervalue "isesxhost=true&vcenterhostid=4460" | select id,hostname

id       hostname
--       --------
26534616 sa-esx8.sa.actifio.com
5552168  sa-esx6.sa.actifio.com
5552166  sa-esx5.sa.actifio.com
5552164  sa-esx1.sa.actifio.com
5552162  sa-esx2.sa.actifio.com
5552160  sa-esx4.sa.actifio.com
5552158  sa-esx7.sa.actifio.com


PS /Users/anthony/git/AGMPowerLib> $esxhostlist = @(5552166,5552168)
PS /Users/anthony/git/AGMPowerLib> $esxhostlist
5552166
5552168
```

I learned my datastore list and made a simple array:
```
PS /Users/anthony/git/AGMPowerLib> $datastorelist = ((Get-AGMHost -id 5552166).sources.datastorelist | select-object name,freespace | sort-object name | Get-Unique -asstring | select name).name

PS /Users/anthony/git/AGMPowerLib> $datastorelist
IBM-FC-V3700
Pure
```

I can now fire my new command:
```
New-AGMLibMultiVM -imagelist $imagelist -vcenterid $vcenterid -esxhostlist $esxhostlist -datastorelist 
```

This will mount all the images in the list and round robin through the ESX host list and data store list.
The VMs get names VMname_imageName

```
PS /Users/anthony/git/AGMPowerLib> New-AGMLibMultiVM -imagelist $imagelist -vcenterid $vcenterid -esxhostlist $esxhostlist -datastorelist $datastorelist -poweronvm false
Mounting AppName: AGM ImageName: Image_26179237 ConsistencyDate: 2020-08-09 11:05:21
Mounting AppName: Ansible ImageName: Image_26179190 ConsistencyDate: 2020-08-09 11:44:31
Mounting AppName: demo-oracle-2 ImageName: Image_26179220 ConsistencyDate: 2020-08-09 11:16:53
Mounting AppName: demo-oracle-5 ImageName: Image_26179182 ConsistencyDate: 2020-08-09 11:07:42
Mounting AppName: demo-sql-3 ImageName: Image_26179242 ConsistencyDate: 2020-08-09 11:00:58
Mounting AppName: demo-sql-4 ImageName: Image_26179210 ConsistencyDate: 2020-08-09 11:27:40
Mounting AppName: demo-sql-5 ImageName: Image_26179201 ConsistencyDate: 2020-08-09 11:39:01
Mounting AppName: demo-sql-6 ImageName: Image_26179243 ConsistencyDate: 2020-08-09 11:00:57
Mounting AppName: demo-sql-7 ImageName: Image_26179248 ConsistencyDate: 2020-08-09 11:00:58
Mounting AppName: demo-sql-8 ImageName: Image_26179241 ConsistencyDate: 2020-08-09 11:00:58
Mounting AppName: demo-sql-9 ImageName: Image_26179236 ConsistencyDate: 2020-08-09 11:01:11
Mounting AppName: File Server ImageName: Image_26183398 ConsistencyDate: 2020-08-09 13:09:38
Mounting AppName: File Server ImageName: Image_26165674 ConsistencyDate: 2020-08-09 01:05:32
Mounting AppName: File Server ImageName: Image_26170635 ConsistencyDate: 2020-08-09 05:06:20
Mounting AppName: File Server ImageName: Image_26176250 ConsistencyDate: 2020-08-09 09:05:03
Mounting AppName: File Server ImageName: Image_26154002 ConsistencyDate: 2020-08-08 17:06:01
Mounting AppName: File Server ImageName: Image_26159647 ConsistencyDate: 2020-08-08 21:05:20
Mounting AppName: Foresight ImageName: Image_26179186 ConsistencyDate: 2020-08-09 11:46:57
Mounting AppName: Linux ImageName: Image_26179172 ConsistencyDate: 2020-08-09 11:12:43
Mounting AppName: Oracle-Mask-Dev ImageName: Image_26179202 ConsistencyDate: 2020-08-09 11:38:37
Mounting AppName: Oracle-Mask-Prd ImageName: Image_26179203 ConsistencyDate: 2020-08-09 11:34:48
Mounting AppName: Oracle-Mask-Stg ImageName: Image_26179197 ConsistencyDate: 2020-08-09 11:40:03
Mounting AppName: SharePoint ImageName: Image_26179191 ConsistencyDate: 2020-08-09 11:44:11
Mounting AppName: SQL-Masking-Dev ImageName: Image_26179212 ConsistencyDate: 2020-08-09 11:13:48
Mounting AppName: SQL-Masking-Prod ImageName: Image_26179176 ConsistencyDate: 2020-08-09 11:54:03
Mounting AppName: sql-masking-stg ImageName: Image_26179211 ConsistencyDate: 2020-08-09 11:25:06
Mounting AppName: Win2k12R2 ImageName: Image_26179229 ConsistencyDate: 2020-08-09 11:01:25
Mounting AppName: Windows ImageName: Image_26176281 ConsistencyDate: 2020-08-09 09:01:40
```

I confirm all of them mounted.

I now clean up using the default label 

```
$mountlist = Get-AGMLibActiveImage | where-object  {$_.label -eq "MultiVM Recovery"}

foreach ($mount in $mountlist.imagename)
{
Remove-AGMMount $mount -d
}
```

I am sure this could be improved.
I am thinking for a start maybe a prefix field for the mounted VM name.
However I thought you might like to see if this is close to what you want.

**Comment by aussiestorblog** [comment] 2020-08-10 07:16
I just uploaded 0.0.0.5

Four improvements:

1)  Added -prefix option so you can set prefix of all VMs
2)  Added -label so you can set label
3)  Added the new VM name to the progress message
4)  Blocked attempt to mount non VMBackup 

Probably the one thing I am not 100% with is the new VM prefix, which is currently the Image Name.
It has give some uniqueness, so its a good choice, but there might be a better choice.

**Comment by kkerr2005** [comment] 2020-08-10 08:40
Hi,

I have to say , this is the best thing ever!

Im just going to run some tests and ill feedback today, thanks for all your hard work

**Comment by kkerr2005** [comment] 2020-08-10 14:40
I seem to have a problem passing in the esx host array, I only have two hosts and im passing in a simple array of ID's.


VCID: 42124
ESXHosts: 42130 42128
Datastore: HyperSwap_02_sv1_labsitea
Folder:  KevsDemo
Prefix: KevDemo_

Press Enter to continue...:
ConvertTo-Json: C:\Users\kkerr\Documents\PowerShell\Modules\AGMPowerLib\0.0.0.5\Public\New-AGMLibMultiVM.ps1:129
Line |
 129 |          $json = $body | ConvertTo-Json
     |                          ~~~~~~~~~~~~~~
     | An item with the same key has already been added. Key: LinkedView

Mounting AppName: compvc ImageName: Image_18210932 ConsistencyDate: 2020-08-09 19:02:32 as: KevDemo_compvc_Image_18210932

err_code    : 10016
err_message : mount is unsuccessful due to ESX host is required.

ConvertTo-Json: C:\Users\kkerr\Documents\PowerShell\Modules\AGMPowerLib\0.0.0.5\Public\New-AGMLibMultiVM.ps1:129
Line |
 129 |          $json = $body | ConvertTo-Json
     |                          ~~~~~~~~~~~~~~
     | An item with the same key has already been added. Key: LinkedView

Mounting AppName: mgmtvc ImageName: Image_18210933 ConsistencyDate: 2020-08-09 19:00:47 as: KevDemo_mgmtvc_Image_18210933

err_code    : 10016
err_message : mount is unsuccessful due to ESX host is required.

**Comment by kkerr2005** [comment] 2020-08-10 15:49
Not sure if this helps, but I changed the depth of the convertto-json to 1

My output now look like this

{
  "@type": "mountRest",
  "label": "KevsDemo",
  "restoreoptions": [
    "System.Collections.Hashtable"
  ],
  "datastore": {
    "FileSystemVersion": "6.81",
    "DatacenterId": "Datacenter-datacenter-2",
    "Datacenter": "Bluechip",
    "ParentFolderId": "StoragePod-group-p3668",
    "ParentFolder": null,
    "DatastoreBrowserPath": "vmstores:\\compvc@443\\Bluechip\\HyperSwap_02_sv1_labsitea",
    "FreeSpaceMB": 637420.0,
    "CapacityMB": 2096896.0,
    "Accessible": true,
    "Type": "VMFS",
    "StorageIOControlEnabled": false,
    "CongestionThresholdMillisecond": 30,
    "State": 0,
    "ExtensionData": "VMware.Vim.Datastore",
    "CapacityGB": 2047.75,
    "FreeSpaceGB": 622.48046875,
    "Name": "HyperSwap_02_sv1_labsitea",
    "Id": "Datastore-datastore-246",
    "Uid": "/VIServer=lab\\kkerr@compvc:443/Datastore=Datastore-datastore-246/"
  },
  "hypervisor": {
    "id": "42128"
  },
  "mgmtserver": {
    "id": 42124
  },
  "vmname": "KevsDemomgmtvc_Image_18210933Test",
  "hostname": "KevsDemomgmtvc_Image_18210933",
  "poweronvm": "True",
  "physicalrdm": 0,
  "rdmmode": "independentvirtual",
  "migratevm": "false"
}

Mounting AppName: mgmtvc ImageName: Image_18210933 ConsistencyDate: 2020-08-09 19:00:47 as: KevsDemomgmtvc_Image_18210933

err_code    : 10040
err_message : payload of mount is not supported

**Comment by aussiestorblog** [comment] 2020-08-11 06:11
So the issue is we are not handling different possible structures.   You can see in the second example the datastore section has every property of the datastore...  all we want is the name.   

So I have added logic to make sure only the name portion of the datastorelist is used.   
Did the same for vcenterid and esxhostlist.

Also added option to instead specify a single esx host ID or datastore name, but since I think you are trying to feed this script by lookups (rather than manually entering), this probably wont help you.

I also updated Get-AGMLibImageRange with two changes:

1)  If you specify -olderlimit and -newerlimit with no consistency date, it will use -olderlimit as a backwards offset and then look forward from there with -newerlimit.   So   if we use -olderlimit 5 -newerlimit 2    then it will look for images that are 5 days old to 3 days old

2)  if you specify -o  it will list snapshot and onvault  images.   it wont remove duplicate consistency dates but New-AGMLibMultiVM will handle this.


Changes will be in version 0.0.0.6

**Comment by kkerr2005** [comment] 2020-08-11 12:53
Thanks Anthony, works perfectly.

One thing though, I have some VM names with "." in them which the Rest post doesnt like , I usually do something like 

$newvmname = $vm.split(".")[0]

which seems to work most of the time before Posting, is this possible within the function?

Thanks

**Comment by aussiestorblog** [comment] 2020-08-12 00:12
Closing as completed

**Closed by aussiestorblog** 2020-08-12 00:12 UTC
